### PR TITLE
Aj/usability updates

### PR DESCRIPTION
**Pull request by ajsingh273**

### CODE REVIEW

**Comment by ajsingh273** [comment]
Tabs:
https://www.pivotaltracker.com/story/show/107532820

**Comment by ajsingh273** [comment]
New navigation:
https://www.pivotaltracker.com/story/show/107527580

**Comment by ajsingh273** [comment]
White space:
https://www.pivotaltracker.com/story/show/107532616

**Comment by ajsingh273** [comment]
@calumhalcrow I made some UI and navigation updates for better usability. Please review and merge if you think its ready. I would like to show Stuart for initial feedback, and then make additional cleanup changes if needed. Thanks.

**Comment by calumhalcrow** [comment]
@ajsingh273 we'll have to remember to update webservices and explorer with the new CSS. For now though I don't have any objection to these changes...

**Pull request merged**
